### ISSUE TITLE
Main text has to have a line break before anything else.

### ISSUE THREAD

**Issue by jtagcat** [jtagcat/signs#1]
Not bothered to fix it, see what I mean by doing ctrl+a and write something in the main text part.

**Comment by janesmae** [comment]
Oh sorry, I have missed the ticket. I was thinking about a potential solution and will see if I can make it happen. The solution basically is centering the content text vertically.

**Comment by janesmae** [comment]
Fixed it, check out my repo for solution or live demo at: https://janesmae.github.io/signs_at_k-space/

**Comment by jtagcat** [comment]
I would note that your repo's text is not editable any more. Braking the core functionality.

**Comment by jtagcat** [comment]
Your repo also doesn't have the current logo. (what is preferred on signs instead of the text).

Also see #2

**Comment by janesmae** [comment]
> I would note that your repo's text is not editable any more. Braking the core functionality.

what browser?

**Comment by janesmae** [comment]
> Your repo also doesn't have the current logo. (what is preferred on signs instead of the text).

Well, i only see that there are couple of forks of my original project, one of them has the logos. None of the forks have made merge requests.

**Comment by janesmae** [comment]
> I would note that your repo's text is not editable any more. Braking the core functionality.

I added back the contenteditable parameter, seems that your browser does not speak the css version of that parameter

**Comment by jtagcat** [comment]
> what browser?
Firefox
> Well, i only see that there are couple of forks of my original project, one of them has the logos. None of the forks have made merge requests.
I thought of doing a MR, but you seemed (and were) inactive. It was also discussed moving the repo under the k-space gh organization.
> I added back the contenteditable parameter, seems that your browser does not speak the css version of that parameter
![image](https://user-images.githubusercontent.com/38327267/76225605-aa0bf600-6214-11ea-916d-99852a003c74.png)
I can now edit, but it seems that now it's misaligned.

**Comment by janesmae** [comment]
The logistics of where you want to keep the repo is up to you. 

Interestingly works on my machine :)

<img width="1680" alt="Screenshot 2020-03-09 at 17 07 28" src="https://user-images.githubusercontent.com/2997606/76228004-cdd93700-6228-11ea-8413-f1381ec58d5e.png">
![Screenshot 2020-03-09 at 17 07 28 (2)](https://user-images.githubusercontent.com/2997606/76228015-d598db80-6228-11ea-9ac4-6c2bc211d2f9.png)
<img width="1680" alt="Screenshot 2020-03-09 at 17 07 08" src="https://user-images.githubusercontent.com/2997606/76228034-dcbfe980-6228-11ea-98c6-567cb3097a40.png">

**Comment by jtagcat** [comment]
I think I found the problem - [LanguageTool](https://addons.mozilla.org/en-US/firefox/addon/languagetool/). As soon as you click it, it misaligns and turning the extension off for the page fixes it fully.
![image](https://user-images.githubusercontent.com/38327267/76318774-1bf84400-62d6-11ea-8d3b-6741bc43a448.png)

Though this is an extension's issue, this bug will probably occur with other extensions adding something to the user input.

**Comment by janesmae** [comment]
Well, you can always file a bug fot the plugin ;)

**Comment by jtagcat** [comment]
Moving to your repo as the main repo (for now, I don't have direct access to the k-space gh organization), created pr #1 there.
